name: SpeedUHC
version: ${project.version}
main: net.banany.speeduhc.SpeedUHC
api-version: 1.8
authors: [vasc]
description: A SpeedUHC Plugin made by vasc
website: https://vasc.dev
commands:
  start:
    description: Starts the game
    permission: speeduhc.start
  healall:
    description: Heals every player that is online.
    permission: speeduhc.admin
  setcounter:
    description: Ignore this command.
